### ISSUE TITLE
method generator

### ISSUE THREAD

**Issue by monperrus** [plum-umd/java-sketch#3]
I try to use a regex generator as follows. It works in sketch (without the class) but fails in jsketch. Any idea?

```
class Test {
harness void test( int x, int y, int z ){
   assert rec(x,y, z) == (x + y) ;
}

generator int rec(int x, int y, int z){ /* automatically rewritten */
   int t = ??;
   if(t == 0){
     return x;
   }   
   if(t == 1){
     return y;
   }

   if(t == 2){
     return z;
   }
   int a = rec(x,y,z);
   int b = rec(x,y,z);

   if(t == 3){
     return a * b;
   }

   if(t == 4){
     return a + b;
   } 

}
}
```

**Comment by jsjeon** [comment]
You may have noticed that all the `harness` methods in the benchmarks are `static`, which are similar to a main entrance method: <code>public static void main(...)</code>.  Similarly, the ways you used `rec` do not have a receiver instance, so it should be `static`, too.

**Comment by jsjeon** [comment]
Besides `static` modifier, the other issue behind this example is method-level `generator`.  (That's why I changed the title of this one.)  In the final solution, we need three _instance_s of method `rec`: 1) at a recursive call for variable `a` (with `t` = 0 or 1); 2) at another recursive call for variable `b` (with `t` = 1 or 1); and 3) at one-upper level, `t` = 4.

Currently, JSketch does not exploit Sketch's `generator` keyword properly.  During the translation, a fixed hole is introduced outside of `rec`, which results in assertion failure: as mentioned above, `t` could be either 0, 1, or 4, i.e., there won't be one solution that satisfies the assertion in the harness.  We can easily avoid that problem by not replacing an expression-level hole.  But, then, the next technical challenge will be instantiating `generator` methods while interpreting Sketch's synthesis results.  This might be similar to how we deal with class-level `generator` we introduced in JSketch, but I'm not sure what other issues will be there.  Let me tackle it step by step, and keep you posted.

**Comment by jsjeon** [comment]
Now holes in a method-level generator are translated as-is so that Sketch can instantiate that generator as well as holes in it.  At least, an assertion failure at Sketch phase won't happen.  See this commit: b557354f12d11e8e1a4d8ca8964da5f92f97b9b1. Synthesized Java files are not correct, though, since JSketch's decoding phase, where we interpret Sketch's synthesis result, is not fixed yet.

**Comment by monperrus** [comment]
this goes fast, thanks.

**Comment by jsjeon** [comment]
Please update the repo and see how JSketch works for `test/t110...` as well as a revised version of your example (i.e., with `static` modifier for harness `test` and generator `rec`).

**Comment by monperrus** [comment]
Solution by Armando & Jinseong:

> wrapping top-level calls to function generator, i.e., not recursive calls inside function generator, but calls in harness or somewhere else.  E.g., in your example, we could introduce another function, say rec1, which just delegates a call to rec, along with the same arguments.  Then, a top-level call, e.g., inside harness test, will be replaced with a call to sort of specialized function (in this case, rec1).  In this way, even after Sketch's inlining, what Sketch has chosen will be inlined into rec1, not harness or other top-level functions, and thus we can collect expressions/statements chosen by Sketch.

and file
```
class Testb290 {
    harness static void test( int x, int y, int z ){
        assert rec(x,y, z) == (x + y + z) ;
    }

    static int rec(int x, int y, int z){ 
        return rec1(x,y,z);
    }

    generator static int rec1(int x, int y, int z){ /* automatically rewritten */
    int t = ??;
    if(t == 0){
        return x;
    }   
    if(t == 1){
        return y;
    }

    if(t == 2){
        return z;
    }
    int a = rec1(x,y,z);
    int b = rec1(x,y,z);

    if(t == 3){
        return a * b;
    }

    if(t == 4){
        return a + b;
    } 
        
    }

}

```
